# Add building/running containers from the top-level makefile
include ../Makefile

.PHONY: test build-service start-service eject

eject:
	npm run eject

test:
	npm run test

build-service:
	npm run build

start-service:
	npm run start