# Add building/running containers from the top-level makefile
include ../Makefile

.PHONY: test build-service dev start-service

test:
	npm run test

build-service:
	npm run build

dev:
	npm run dev

start-service:
	npm run start